In [1]:
import torch
from torch.distributions import Normal

In [5]:
normal = Normal(torch.tensor([10., 3., 2.]), torch.tensor([0.1, 0.3, 0.01]))

In [8]:
normal.rsample((10,))

tensor([[10.0702,  2.7801,  2.0065],
        [10.1733,  3.3108,  1.9935],
        [ 9.9618,  3.3420,  1.9999],
        [ 9.8370,  2.8092,  1.9883],
        [ 9.9498,  3.2655,  1.9856],
        [ 9.9487,  2.7257,  2.0004],
        [10.0464,  2.7804,  1.9965],
        [10.0168,  3.3529,  2.0062],
        [ 9.8994,  2.9496,  1.9886],
        [ 9.9654,  2.7931,  1.9961]])

In [2]:
import pandas as pd
import pickle

# 前処理済みデータセットについてみる

In [18]:
all_data = pickle.load(
    open("/home/inoue/work/dataset/RC15/derived/train_valid.df", "rb"))
all_data 

{'session': array([    0,     0,     0, ..., 19116, 19116, 19116]),
 'state': array([[    0,     0,     0, ...,     0,     0, 12042],
        [    0,     0,     0, ...,     0, 12042,  1016],
        [    0,     0,     0, ..., 12042,  1016, 12042],
        ...,
        [    0,     0,     0, ..., 15680, 15665, 15676],
        [    0,     0,     0, ..., 15665, 15676, 15665],
        [    0,     0,     0, ..., 15676, 15665, 15676]]),
 'action': array([ 1016, 12042,   864, ..., 15665, 15676, 15680]),
 'reward': array([0.2, 0.2, 0.2, ..., 0.2, 1. , 1. ]),
 'n_state': array([[    0,     0,     0, ...,     0, 12042,  1016],
        [    0,     0,     0, ..., 12042,  1016, 12042],
        [    0,     0,     0, ...,  1016, 12042,   864],
        ...,
        [    0,     0,     0, ..., 15665, 15676, 15665],
        [    0,     0,     0, ..., 15676, 15665, 15676],
        [    0,     0, 15676, ..., 15665, 15676, 15680]]),
 'done': array([0, 0, 0, ..., 0, 0, 1])}

In [19]:
pd.DataFrame(all_data["reward"]).value_counts()

0.2    189903
1.0     62345
dtype: int64

In [22]:
all_data["state"], all_data["action"]

(array([[    0,     0,     0, ...,     0,     0, 12042],
        [    0,     0,     0, ...,     0, 12042,  1016],
        [    0,     0,     0, ..., 12042,  1016, 12042],
        ...,
        [    0,     0,     0, ..., 15680, 15665, 15676],
        [    0,     0,     0, ..., 15665, 15676, 15665],
        [    0,     0,     0, ..., 15676, 15665, 15676]]),
 array([ 1016, 12042,   864, ..., 15665, 15676, 15680]))

# 推薦結果を見てみる

In [29]:
for k in [5, 10, 20]:
    result = pd.read_csv("/home/inoue/work/program_016_inoue/master_programs/results/RC15/result@%d.csv"%k)
    display(result[result["ClickType"] == "click"].sort_values(["Hit@%d"%k, "NDCG@%d"%k]))
    display(result[result["ClickType"] == "purchase"].sort_values(["Hit@%d"%k, "NDCG@%d"%k]))


Model ClickType     Hit@5    NDCG@5
8  GRUDQNRec     click  0.001268  0.001399
4  GRUSACRec     click  0.157928  0.148869
6  GRUBCQRec     click  0.230867  0.237207
0    GRU4Rec     click  0.305920  0.297169
2  GRUSQNRec     click  0.316860  0.310525

Model ClickType     Hit@5    NDCG@5
9  GRUDQNRec  purchase  0.000952  0.001034
5  GRUSACRec  purchase  0.271689  0.253653
7  GRUBCQRec  purchase  0.308644  0.309327
1    GRU4Rec  purchase  0.398097  0.378308
3  GRUSQNRec  purchase  0.407613  0.384474

Model ClickType    Hit@10   NDCG@10
8  GRUDQNRec     click  0.001956  0.001708
4  GRUSACRec     click  0.227431  0.181372
6  GRUBCQRec     click  0.254440  0.248564
0    GRU4Rec     click  0.406448  0.344274
2  GRUSQNRec     click  0.420190  0.359013

Model ClickType    Hit@10   NDCG@10
9  GRUDQNRec  purchase  0.002538  0.001752
7  GRUBCQRec  purchase  0.346550  0.327580
5  GRUSACRec  purchase  0.382078  0.305544
1    GRU4Rec  purchase  0.536082  0.442988
3  GRUSQNRec  purchase  0.545123  0.448914

Model ClickType    Hit@20   NDCG@20
8  GRUDQNRec     click  0.003383  0.002231
6  GRUBCQRec     click  0.259619  0.250514
4  GRUSACRec     click  0.292495  0.205153
0    GRU4Rec     click  0.488742  0.374357
2  GRUSQNRec     click  0.505391  0.390139

Model ClickType    Hit@20   NDCG@20
9  GRUDQNRec  purchase  0.006027  0.003004
7  GRUBCQRec  purchase  0.355591  0.331042
5  GRUSACRec  purchase  0.474227  0.339167
1    GRU4Rec  purchase  0.647740  0.483863
3  GRUSQNRec  purchase  0.655036  0.489151

In [27]:
result[result["ClickType"] == "purchase"].sort_values(["Hit@10", "NDCG@10"])

Model    Hit@10   NDCG@10 ClickType
7  GRUDQNRec  0.002538  0.001752  purchase
5  GRUBCQRec  0.346550  0.327580  purchase
3  GRUSACRec  0.382078  0.305544  purchase
1    GRU4Rec  0.536082  0.442988  purchase
9  GRUSQNRec  0.545123  0.448914  purchase

In [3]:
gru_sqn_recs = pd.read_csv("/home/inoue/work/program_016_inoue/master_programs/results/RC15/GRUSQNRec_rec_result.csv")

In [5]:
gru_sqn_recs.rename(columns={"0":"sessionId", "1":"selected_item"})

sessionId  selected_item      2      3      4      5      6      7  \
0          19101          13811      0      0      0      0      0      0   
1          13430           7768      0      0      0      0      0      0   
2          15389          14996      0      0      0      0      0  14980   
3           7490           7371      0      0      0      0      0      0   
4          12844          13422      0      0      0      0      0      0   
...          ...            ...    ...    ...    ...    ...    ...    ...   
25220      15230          11259  11254  11256  11257  11259  11260  11262   
25221      11720          14443      0      0      0      0      0  14443   
25222      18573          15488      0      0      0      0      0      0   
25223      18025           9621      0      0      0      0      0   9258   
25224      15161          15033      0      0      0      0      0  15020   

           8      9  ...     12     13     14     15     16     17     18  \
0          0      0  ...  14865  12770  14874   3085  15208  14904     38   
1          0      0  ...   4865  14624   7768  14606  14567  13534   9135   
2      14025  10789  ...  10789   8579   7714  14980  14630  14970  13762   
3          0      0  ...  13536   9781  12642  11091  12640  12643   3869   
4      13433   1789  ...  13433  13422   1790   1789   4085  13441  13442   
...      ...    ...  ...    ...    ...    ...    ...    ...    ...    ...   
25220  11262  14682  ...  11257  11256  11259  11315    378  11262  11320   
25221  14443  11186  ...  13560  14443  13609  14448  11186   6470  14446   
25222      0      0  ...   8042  11510   5847  12495   6228  14943   6925   
25223  14867  11121  ...  11114   8582  14261  14272  14867    132  11121   
25224  15033  15022  ...  15020  15025  15042  15029  15033  15018  15019   

          19     20     21  
0      14227  13370   8317  
1       7777  14573  14488  
2       6208  14983  14631  
3      12535   3220   3883  
4      13440  10576  10592  
...      ...    ...    ...  
25220  11260  14373  15753  
25221  11101  14457  11102  
25222  13426   9424   4814  
25223  15231  15240  11160  
25224  15022  14965  15093  

[25225 rows x 22 columns]

In [6]:
for i in [1, 5, 20, 3, 22]:
    print("--------------------------------------------------------")
    print("state: ", gru_sqn_recs.loc[i, "2":"11"].values)
    print("recommend: ", gru_sqn_recs.loc[i, "12":].values) 
    print("trueId: ", gru_sqn_recs.loc[i, "1"])

--------------------------------------------------------
state:  [    0     0     0     0     0     0     0     0  7768 14624]
recommend:  [ 4865 14624  7768 14606 14567 13534  9135  7777 14573 14488]
trueId:  7768
--------------------------------------------------------
state:  [10562  2525  6661 13715  8039 12529  8039 11077 13884  9686]
recommend:  [ 9685  2286 14636  9684 11372 10431  8039     6 14633  9686]
trueId:  9685
--------------------------------------------------------
state:  [    0     0     0     0     0     0  5961  5974   286 11916]
recommend:  [  286 11916 13595  5974  5961 13593   424 10684  3657   275]
trueId:  11916
--------------------------------------------------------
state:  [    0     0     0     0     0     0     0     0 13536  9781]
recommend:  [13536  9781 12642 11091 12640 12643  3869 12535  3220  3883]
trueId:  7371
--------------------------------------------------------
state:  [    0     0     0     0 12637 14536 14563  9765 14536 14563]
recommend:  

In [14]:
import numpy as np
gru_sqn_recs.loc[:, "1":"11"].apply(
    lambda x: np.sum(x[0] == x[1:].values) > 0, axis=1
)

0        False
1         True
2        False
3        False
4        False
         ...  
25220     True
25221     True
25222    False
25223    False
25224     True
Length: 25225, dtype: bool

In [26]:
select_item_not_in_hist_idx = gru_sqn_recs[gru_sqn_recs.loc[:, "1":"11"].apply(
    lambda x: np.sum(x[0] == x[1:].values) == 0, axis=1
)].index

select_item_not_in_hist_and_recommend_idx = gru_sqn_recs.loc[select_item_not_in_hist_idx, :][pd.concat([gru_sqn_recs.loc[select_item_not_in_hist_idx, "1"], gru_sqn_recs.loc[select_item_not_in_hist_idx, "12":]], axis=1).apply(
    lambda x: np.sum(x[0] == x[1:].values) != 0, axis=1
    )].index

In [28]:
select_item_not_in_hist_and_recommend_idx.shape

(3900,)

In [35]:
random_samples = np.random.choice(select_item_not_in_hist_and_recommend_idx, size=6)

for i in random_samples:
    print("--------------------------------------------------------")
    print("state: ", gru_sqn_recs.loc[i, "2":"11"].values)
    print("recommend: ", gru_sqn_recs.loc[i, "12":].values) 
    print("trueId: ", gru_sqn_recs.loc[i, "1"])

--------------------------------------------------------
state:  [    0     0     0     0     0     0     0  4658  4664 12221]
recommend:  [11938  7109  3255 12402  1467 14201 14251  4650 10887 11740]
trueId:  7109
--------------------------------------------------------
state:  [   0    0    0    0    0    0    0    0 3535 8461]
recommend:  [ 3535 12235 12646 14336 14468 11598  8461  8588 14876 13785]
trueId:  14876
--------------------------------------------------------
state:  [   0    0    0    0    0    0    0    0 7714 1595]
recommend:  [ 7714  8579 11587 11740  6208  9649  1595  9601  7715  8580]
trueId:  9649
--------------------------------------------------------
state:  [    0     0     0     0     0     0     0 10989  1540   986]
recommend:  [10989 13572  9761 12765   723 14985 14763 10908 10541 13573]
trueId:  723
--------------------------------------------------------
state:  [    0     0 13424 13404 11584 13405 11228 13406  2083 11584]
recommend:  [ 2083 13405 13406 10